stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - data/heart.csv
      - preprocess.py
    outs:
      - data/processed_data.csv

  train:
    cmd: python train.py
    deps:
      - data/processed_data.csv
      - train.py
    outs:
      - models/model.pkl
    metrics:
      - metrics/metrics.json

  evaluate:
    cmd: python evaluate.py
    deps:
      - models/model.pkl
      - data/processed_data.csv
      - evaluate.py
    outs:
      - reports/evaluation_report.json
